name: Gemini Code Review

on:
  push:
    branches: [ feature/gemini ]
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get changed files for PR
        if: github.event_name == 'pull_request'
        id: changed-files-pr
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          grep "\.kt$" changed_files.txt > kotlin_files.txt || true
          if [ -s kotlin_files.txt ]; then
            echo "KOTLIN_FILES_EXISTS=true" >> $GITHUB_ENV
          else
            echo "KOTLIN_FILES_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Get changed files for Push
        if: github.event_name == 'push'
        id: changed-files-push
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          grep "\.kt$" changed_files.txt > kotlin_files.txt || true
          if [ -s kotlin_files.txt ]; then
            echo "KOTLIN_FILES_EXISTS=true" >> $GITHUB_ENV
          else
            echo "KOTLIN_FILES_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Review code with Gemini AI
        if: env.KOTLIN_FILES_EXISTS == 'true'
        id: gemini-review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          GEMINI_ENDPOINT="https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GEMINI_API_KEY}"
          
          REVIEW_COMMENT="## Gemini AI 코드 리뷰 결과\n\n"
          
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              echo "리뷰 중: $file"
          
              FILE_CONTENT=$(cat "$file")
          
              REQUEST_BODY='{
                "contents": [
                  {
                    "parts": [
                      {
                        "text": "다음 Kotlin 코드를 검토하고 코드 품질, 가독성, 성능 및 보안 관점에서 개선점과 피드백을 제공해주세요. 특별히 강조할 중요한 이슈가 있다면 먼저 언급해주세요. 응답은 마크다운 형식의 간결한 한국어로 작성해주세요.\n\n파일 경로: '"$file"'\n\n코드:\n```kotlin\n'"$FILE_CONTENT"'\n```"
                      }
                    ]
                  }
                ],
                "generationConfig": {
                  "temperature": 0.2,
                  "topK": 40,
                  "topP": 0.95,
                  "maxOutputTokens": 8192
                }
              }'
          
              RESPONSE=$(curl -s -X POST "$GEMINI_ENDPOINT" \
                -H "Content-Type: application/json" \
                -d "$REQUEST_BODY")
          
              REVIEW_TEXT=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          
              REVIEW_COMMENT+="### ${file}\n\n${REVIEW_TEXT}\n\n---\n\n"
            fi
          done < kotlin_files.txt
          
          echo "$REVIEW_COMMENT" > gemini_review.md
          
          if [ $(wc -c < gemini_review.md) -gt 65000 ]; then
            echo "리뷰 내용이 너무 깁니다. 요약 버전을 생성합니다."
            head -c 60000 gemini_review.md > gemini_review_truncated.md
            echo "\n\n... (리뷰가 너무 길어 잘렸습니다. 전체 리뷰는 워크플로우 아티팩트에서 확인하세요) ..." >> gemini_review_truncated.md
            mv gemini_review_truncated.md gemini_review.md
          fi
          
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "===== Gemini Code Review Results ====="
            cat gemini_review.md
            echo "======================================"
          fi

      - name: Upload review artifact
        if: env.KOTLIN_FILES_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gemini-code-review
          path: gemini_review.md

      - name: Add PR comment
        if: env.KOTLIN_FILES_EXISTS == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('gemini_review.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });